### ISSUE TITLE
Please add a licence file (or two).

### ISSUE THREAD

**Issue by dglaude** [theacodes/Winterbloom-Hostess-FeatherWing#1]
There might be a way to let GitHub know that the licence is MIT so that it put the file for you and classify it. That way at first glance, without reading the readme, it is clear and follow in fork.

**Comment by theacodes** [comment]
I'd rather not put a license in the top-level, as I don't want to mistakenly have github classify the entire repo as MIT (or have people assume that the whole repo is MIT), since the code and hardware are under distinct licenses.
